# Generated by Django 2.2.3 on 2019-09-11 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oilchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of last oil change')),
                ('mileage', models.IntegerField()),
                ('oil_brand', models.CharField(max_length=25)),
                ('filter_brand', models.CharField(max_length=25)),
                ('air_filter', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='N', max_length=1, verbose_name='Air filter changed?')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Car')),
            ],
        ),
    ]
