# Generated by Django 2.2.3 on 2019-09-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_oilchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilchange',
            name='air_filter',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='n', max_length=1, verbose_name='Air filter changed?'),
        ),
    ]
