# Generated by Django 2.2.3 on 2019-09-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_car_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilchange',
            name='air_filter',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='Air filter changed?'),
        ),
    ]
